### ISSUE TITLE
setup_drchecker.py should error out if no output directory specified

### ISSUE THREAD

**Issue by ajdlinux** [ucsb-seclab/dr_checker#1]
If you run setup_drchecker.py with no arguments it throws an unhelpful exception rather than displaying a usage message.

```
ajd@intelligence:~/code/dr_checker/helper_scripts$ python setup_drchecker.py 
Traceback (most recent call last):
  File "setup_drchecker.py", line 112, in <module>
    main()
  File "setup_drchecker.py", line 58, in main
    sparse_dir = os.path.join(parsed_args.output_folder, "sparse")
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by ajdlinux** [comment]
cheers @Machiry!
