### ISSUE TITLE
Clang/LLVM 10 run where SoundyAnalysisRunner fails

### ISSUE THREAD

**Issue by ghost** [ucsb-seclab/dr_checker#39]
Any ideas why the SoundyAnalysisRunner fails?

It makes the Bitcode, links it (with dr_linker), finds entrypoints etc.

Also had to disable c2xml since it was complaining on malformed input.
```

    def perform(self):
        """
            Parse the headers
        :return: True or False
        """
        return True
```

With it enabled, it errors out:
```

[*]  Trying to run 339 c2xml commands in parallel.
Traceback (most recent call last):
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 167, in <module>
    main()
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 115, in main
    ret_val = __run_component(curr_comp, component_times)
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 140, in __run_component
    ret_val = component_obj.perform()
  File "/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/dr_checker/helper_scripts/runner_scripts/components/parse_headers.py", line 72, in perform
    dst_work_dir=self.separate_out)
  File "/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/dr_checker/helper_scripts/runner_scripts/components/parse_headers.py", line 183, in _run_c2xml
    all_hdr_entries = p.map(_run_single_c2xml, to_run_cmds)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
xml.etree.ElementTree.ParseError: unclosed token: line 542, column 4

```

Files:

```
root@2b99150e60d3:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1# ls -lt /tmp
total 37340
-rw-r--r--  1 root root       0 Aug 26 18:18 fpga-mgr.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 hwmon.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 pci-epf.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 spi-mem.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 iomap.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 of_reserved_mem.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 kernfs.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 kvm_host.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 suspend.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 moduleparam.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 driver.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ipack.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 pci-acpi.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 shdma-base.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ide.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 vga_switcheroo.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 elevator.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 host.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 vexpress.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 frontswap.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 lightnvm.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 phy.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 otg-fsm.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 serial_8250.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 nfs_page.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 sysfs.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 gadget.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 dca.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 net.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 typec_altmode.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 virtio_config.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 reset-controller.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 serdev.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 libnvdimm.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 rtsx_pci.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 mroute_base.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 scmi_protocol.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 dma-fence.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 mailbox_controller.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 phylink.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 rbtree_latch.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 atmdev.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 bpf.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 auth.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 sw_trigger.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 buffer-dma.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ntb.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 sw_device.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 trigger.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 serial_core.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 configfs.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 iio.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 lcd.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 libata.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 master.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 wm97xx.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 rtc.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 clk-provider.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 gnss.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 sh_clk.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 pci-epc.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 dcache.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 powercap.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ethtool.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 morus1280_glue.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 vfio.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 kobject.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 acpi_bus.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 morus640_glue.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 drbg.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 led-class-flash.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 tty.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 rdma_netlink.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 mc.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 thermal.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ib_verbs.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 smem_state.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ss.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 cxl.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 messenger.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 qmi.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 v4l2-async.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 media-entity.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 target_core_fabric.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 fs_context.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 v4l2-dev.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 iscsi_target_core.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 psci.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 media-devnode.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 target_core_backend.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 asoc.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 net_namespace.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 blkdev.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 parport.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 fscrypt.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 posix-clock.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 hcd.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 bpfilter.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 bcma.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 fs.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 rfkill.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 efi.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 i2c.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 quota.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 oprofile.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 ppp_channel.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 tty_driver.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 bind.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 dax.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 pci.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 atm_tcp.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 seq_file.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 libfc.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 coresight.h.hdrout
-rw-r--r--  1 root root       0 Aug 26 18:18 scsi_cmnd.h.hdrout
-rw-r--r--  1 root root   31292 Aug 26 18:18 198118_hdrs.txt
```

198118_hdrs.txt

seems ok

```
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/i2c.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/hdmi-codec.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/soc.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/soc-topology.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/hdaudio.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/rawmidi.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/compress_driver.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/vx_core.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/hda_chmap.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/pcm.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/soc-dai.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/hwdep.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/simple_card_utils.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/ac97_codec.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/omap-hdmi-audio.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/ac97/controller.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/sb16_csp.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/hda_codec.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/sound/core.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/video/sh_mobile_lcdc.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/video/omapfb_dss.h
/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/include/video/mmp_disp.h
```

Here is the issue where SoundAnalysis fails:

```
[*]  To link folder:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final
cp: '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/input.llvm.bc' and '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/input.llvm.bc' are the same file
cp: '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/final_to_check.bc' and '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/final_to_check.bc' are the same file
cp: '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/property.llvm.bc' and '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/property.llvm.bc' are the same file
cp: '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/core.llvm.bc' and '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/core.llvm.bc' are the same file
cp: '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/of_touchscreen.llvm.bc' and '/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/of_touchscreen.llvm.bc' are the same file
error: Linking globals named 'platform_notify': symbol multiply defined!
[+]  To check BC file:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/final_to_check.bc
[+]  Component: DrLinker  ran successfully.
[+]  Component: DrLinker  passed successfully.
[*]  Trying to Run Component: ParseHeaders
[+]  Setup for component: ParseHeaders  complete
[+]  Component: ParseHeaders  ran successfully.
[+]  Component: ParseHeaders  passed successfully.
[*]  Trying to Run Component: EntryPointIdentifier
[+]  Setup for component: EntryPointIdentifier  complete
[*]  Running EntryPointIdentifier..
[+]  Entry point file present:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/hdr_file_config.txt
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/keyboard/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/mouse/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/serio/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/llvm_link_final/final_to_check.bc
[*]  EntryPointIdentifier Processing:/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/touchscreen/llvm_link_final/final_to_check.bc
[+]  Successfully generated all the possible entry points into file: /laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/linux-5.3.1/bitout1/entry_point_out.txt
[+]  Component: EntryPointIdentifier  ran successfully.
[+]  Component: EntryPointIdentifier  passed successfully.
[*]  Trying to Run Component: SoundyAnalysisRunner
[+]  Setup for component: SoundyAnalysisRunner  complete
[*]  Invoking Soundy Checker
[*]  Found: 15  entry points to process.
[*]  Processing in multiprocessing mode
[*]  Finished processing: 15  entry points.
[!]  Soundy Analysis failed for: atkbd_do_set_extra
[!]  Soundy Analysis failed for: atkbd_do_set_force_release
[!]  Soundy Analysis failed for: atkbd_do_set_scroll
[!]  Soundy Analysis failed for: atkbd_do_set_set
[!]  Soundy Analysis failed for: atkbd_do_set_softrepeat
[!]  Soundy Analysis failed for: atkbd_do_set_softraw
[!]  Soundy Analysis failed for: raw_table_read
[!]  Soundy Analysis failed for: bind_mode_store
[!]  Soundy Analysis failed for: drvctl_store
[!]  Soundy Analysis failed for: serio_set_bind_mode
[!]  Soundy Analysis failed for: uevent_store
[!]  Soundy Analysis failed for: unbind_store
[!]  Soundy Analysis failed for: bind_store
[!]  Soundy Analysis failed for: serport_ldisc_ioctl
[!]  Soundy Analysis failed for: serport_ldisc_compat_ioctl
[*]  Soundy Analysis failed for: 15  out of: 15  entry points.
[+]  Component: SoundyAnalysisRunner  ran successfully.
[+]  Component: SoundyAnalysisRunner  passed successfully.
[*]  Trying to Run Component: ComputeWarningStats
[+]  Setup for component: ComputeWarningStats  complete
[*]  Invoking Warnings Stats Computation.
Traceback (most recent call last):
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 167, in <module>
    main()
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 115, in main
    ret_val = __run_component(curr_comp, component_times)
  File "../dr_checker/helper_scripts/runner_scripts/run_all.py", line 140, in __run_component
    ret_val = component_obj.perform()
  File "/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/dr_checker/helper_scripts/runner_scripts/components/warnings_stats.py", line 31, in perform
    ret_val = _run_multi_warnings_json(self.soundy_analysis_out, self.output_stats_csv)
  File "/laptop/media/mk/4e3f0810-c5e8-4a7f-a629-2800a1356ebd/dr_checker/helper_scripts/runner_scripts/components/warnings_stats.py", line 129, in _run_multi_warnings_json
    footer = "TOTAL," + str(warnings_total['total'])
KeyError: 'total'
```

Thanks in advance

Cc @Machiry

**Comment by ghost** [comment]
Found the problem:

```
opt: Unknown command line argument '-debug'.
```

After removing it from cmd line it works.

Not sure about headers files and c2xml

Running now Dr_Checker on Linux Kernel 5.3.1 drivers. Will see if it will work and find anything.

**Comment by ghost** [comment]
c2xml is needed. Sometimes c2xml produces errors, due to missing headers (weird?). I will just skip on malformed XML.
